# Generated by Django 4.1.6 on 2023-03-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_user_post_artwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Album',
        ),
    ]
